USE book_exchange;

INSERT INTO books (id, title, course_number, cover_image_url) VALUES
(1, 'Discrete Mathematics: Set Theory, Combinatorics and Graph Theory', 20476, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(2, 'Linear Algebra I', 20109, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(3, 'Infinitesimal Calculus I', 20106, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(4, 'Differential and Integral Calculus II', 20423, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(5, 'Probability for Computer Science Students', 20425, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(6, 'Logic for Computer Science', 20466, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(7, 'Introduction to Computer Science Using Java', 20441, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(8, 'Data Structures and Introduction to Algorithms', 20407, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(9, 'Algorithms', 20417, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(10, 'Automata Theory and Formal Languages', 20440, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(11, 'System Programming Laboratory', 20465, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(12, 'Introduction to the Theory of Computation and Complexity', 20585, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(13, 'Operating Systems', 20594, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(14, 'Seminar or workshop in Computer Science', 0, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(15, 'Digital Design', 20272, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(16, 'Computer Organization', 20471, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(17, 'Database Systems', 20277, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(18, 'Principles of Information Systems Development', 20436, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(19, 'Algorithmics: The Foundations of Computer Science', 20290, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(20, 'Introduction to Coding Theory', 20296, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(21, 'Numerical Analysis I', 20462, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(22, 'Advanced Programming with Java', 20554, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(23, 'Prolog and Artificial Intelligence', 20596, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(24, 'Introduction to Artificial Intelligence', 20551, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(25, 'Biological Computation', 20581, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(26, 'Introduction to Computer Networks', 20582, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(27, 'Computer Graphics', 20562, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(28, 'Introduction to Cryptography', 20580, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(29, 'Compilation', 20364, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(30, 'Programming Languages', 20905, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(31, 'Database Systems Implementation', 20574, 'https://blocks.astratic.com/img/general-img-landscape.png'),
(32, 'Data Mining', 20595, 'https://blocks.astratic.com/img/general-img-landscape.png');
