import { Book, User, BookRequest } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Dr. Sarah Chen',
    email: 'schen@university.edu',
    role: 'faculty',
    department: 'Computer Science',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150&h=150',
  },
  {
    id: '2',
    name: 'Alex Thompson',
    email: 'athompson@university.edu',
    role: 'student',
    department: 'Mathematics',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=150&h=150',
  },
];

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    edition: '4th Edition',
    condition: 'Very Good',
    subject: 'Computer Science',
    available: true,
    ownerId: '1',
    owner: mockUsers[0],
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=300',
    description: 'The latest edition of the essential text in algorithms. Minimal highlighting, no damage.',
  },
  {
    id: '2',
    title: 'Abstract Algebra',
    author: 'David S. Dummit',
    edition: '3rd Edition',
    condition: 'Good',
    subject: 'Mathematics',
    available: true,
    ownerId: '2',
    owner: mockUsers[1],
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=300',
    description: 'Perfect for advanced mathematics students. Some notes in margins that might be helpful.',
  },
  {
    id: '3',
    title: 'Computer Networks',
    author: 'Andrew S. Tanenbaum',
    edition: '5th Edition',
    condition: 'Like New',
    subject: 'Computer Science',
    available: true,
    ownerId: '1',
    owner: mockUsers[0],
    coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=300',
    description: 'Comprehensive coverage of computer networks from the physical layer to the application layer.',
  },
  {
    id: '4',
    title: 'Linear Algebra and Its Applications',
    author: 'Gilbert Strang',
    edition: '5th Edition',
    condition: 'Very Good',
    subject: 'Mathematics',
    available: true,
    ownerId: '2',
    owner: mockUsers[1],
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=300',
    description: 'Essential text for understanding linear algebra with real-world applications.',
  },
  {
    id: '5',
    title: 'Database System Concepts',
    author: 'Abraham Silberschatz',
    edition: '7th Edition',
    condition: 'Good',
    subject: 'Computer Science',
    available: true,
    ownerId: '1',
    owner: mockUsers[0],
    coverImage: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&q=80&w=300',
    description: 'Comprehensive introduction to database systems with practical examples.',
  },
  {
    id: '6',
    title: 'Real Analysis',
    author: 'Walter Rudin',
    edition: '3rd Edition',
    condition: 'Good',
    subject: 'Mathematics',
    available: true,
    ownerId: '2',
    owner: mockUsers[1],
    coverImage: 'https://images.unsplash.com/photo-1584697964358-3e14ca57658b?auto=format&fit=crop&q=80&w=300',
    description: 'Classic text on real analysis, perfect for advanced mathematics students.',
  },
  {
    id: '7',
    title: 'Operating System Concepts',
    author: 'Abraham Silberschatz',
    edition: '10th Edition',
    condition: 'Like New',
    subject: 'Computer Science',
    available: true,
    ownerId: '1',
    owner: mockUsers[0],
    coverImage: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&q=80&w=300',
    description: 'Comprehensive coverage of operating systems with practical examples.',
  },
  {
    id: '8',
    title: 'Discrete Mathematics and Its Applications',
    author: 'Kenneth H. Rosen',
    edition: '8th Edition',
    condition: 'Very Good',
    subject: 'Both',
    available: true,
    ownerId: '2',
    owner: mockUsers[1],
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=300',
    description: 'Essential text for both computer science and mathematics students.',
  },
  {
    id: '9',
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell',
    edition: '4th Edition',
    condition: 'New',
    subject: 'Computer Science',
    available: true,
    ownerId: '1',
    owner: mockUsers[0],
    coverImage: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=300',
    description: 'Comprehensive introduction to artificial intelligence and machine learning.',
  },
  {
    id: '10',
    title: 'Complex Analysis',
    author: 'Lars V. Ahlfors',
    edition: '3rd Edition',
    condition: 'Good',
    subject: 'Mathematics',
    available: true,
    ownerId: '2',
    owner: mockUsers[1],
    coverImage: 'https://images.unsplash.com/photo-1576153192396-180ecef2a715?auto=format&fit=crop&q=80&w=300',
    description: 'Classic text on complex analysis for advanced mathematics students.',
  }
];

export const mockRequests: BookRequest[] = [
  {
    id: '1',
    bookId: '1',
    requesterId: '2',
    ownerId: '1',
    status: 'pending',
    message: 'Would love to borrow this for the upcoming semester!',
    createdAt: '2024-03-10T10:00:00Z',
  },
];